name: scgpt_flow_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Interpreters 
  - python=3.10
  - r-base=4.4
  
  # Python Libraries
  - boto3
  - requests
  - pandas
  - openai
  - python-dotenv
  
  # R Libraries from Conda-Forge/Bioconda
  - r-seurat=5.4.0
  - r-remotes
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-matrix
  - r-mclust
  - r-optparse
  - r-cluster
  - r-flexmix
  - r-harmony
  - bioconductor-biocparallel
  - bioconductor-singlecellexperiment
  - bioconductor-summarizedexperiment
  - libxml2 
  - openssl
